name = "short-link-worker"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "short-link-db"
database_id = "8d03bb50-cb57-4b1d-bc0d-15edb4f50b0b"
